const mongoose = require("mongoose");

const CarModelSchema = new mongoose.Schema({
  model: {
    type: String,
    require: true,
    enum: [
      "City IVTEC",
      "Civic VTi Oriel Prosmatec",
      "Civic EXi",
      "City IDSI",
      "City Aspire",
      "Alto",
      "Alto Lapin",
      "APV",
      "Baleno",
      "Bolan",
      "Cappuccino",
      "Carry",
      "Celerio",
      "Cervo",
      "Ciaz",
      "Cultus VX",
      "Cultus VXL",
      "Cultus VXR",
      "Escudo",
      "Every",
      "Every Wagon",
      "FX",
      "Hustler",
      "Ignis",
      "Jimny",
      "Jimny Sierra",
      "Kei",
      "Khyber",
      "Kizashi",
      "Liana",
      "Lj80",
      "Margalla",
      "Mega Carry Xtra",
      "Mehran VX",
      "Mehran VXR",
      "MR Wagon",
      "Palette",
      "Palette Sw",
      "Potohar",
      "Ravi",
      "Samurai",
      "Sj410",
      "Solio",
      "Solio Bandit",
      "Spacia",
      "Swift",
      "Sx4",
      "Twin",
      "Vitara",
      "Wagon R",
      "Wagon R Stingray",
      "Allion",
      "Alphard",
      "Alphard Hybrid",
      "Altis Grande",
      "Aqua",
      "Auris",
      "Avanza",
      "Avensis",
      "Aygo",
      "B B",
      "Belta",
      "C-HR",
      "Cami",
      "Camry",
      "Carina",
      "Celica",
      "Chaser",
      "Coaster",
      "Corolla 2.0 D",
      "Corolla Assista",
      "Corolla Axio",
      "Corolla Cross",
      "Corolla Fielder",
      "Corolla GLI",
      "Corolla XE",
      "Corolla XLI",
      "Corona",
      "Corrolla Altis",
      "Cressida",
      "Cresta",
      "Crown",
      "Duet",
      "Echo",
      "Esquire",
      "Estima",
      "Fielder",
      "Fj Cruiser",
      "Fortuner",
      "Fortuner G",
      "Fortuner Legender",
      "Fortuner Sigma",
      "Fortuner V",
      "Harrier",
      "Hiace",
      "Hilux",
      "iQ",
      "ISIS",
      "IST",
      "Kluger",
      "Land Cruiser",
      "Lite Ace",
      "Lucida",
      "Mark II",
      "Mark X",
      "MR2",
      "Noah",
      "Passo",
      "Pickup",
      "Pixis Epoch",
      "Platz",
      "Porte",
      "Prado",
      "Premio",
      "Previa",
      "Prius",
      "Prius Alpha",
      "Probox",
      "Ractis",
      "Raize",
      "Raum",
      "Rav4",
      "Roomy",
      "Rush",
      "Sera",
      "Sienta",
      "Spacio",
      "Sprinter",
      "Starlet",
      "Succeed",
      "Supra",
      "Surf",
      "Tacoma",
      "Town Ace",
      "Toyo Ace",
      "Tundra",
      "Urban Cruiser",
      "Van",
      "Vanguard",
      "Verossa",
      "Vitz",
      "Voxy",
      "Wish",
      "Yaris",
      "Audi A1",
      "Audi A3",
      "Audi A4",
      "Audi A5",
      "Audi A6",
      "Audi A7",
      "Audi A8",
      "Audi E-Tron",
      "Audi Q2",
      "Audi Q3",
      "Audi Q5",
      "Audi Q7",
      "Audi R8",
      "Audi Tt",
      "Audi E-tron Gt",
      "Alto",
      "Alto Lapin",
      "APV",
      "Baleno",
      "Bolan",
      "Cappuccino",
      "Carry",
      "Celerio",
      "Cervo",
      "Ciaz",
      "Cultus VX",
      "Cultus VXL",
      "Cultus VXR",
      "Escudo",
      "Every",
      "Every Wagon",
      "FX",
      "Hustler",
      "Ignis",
      "Jimny",
      "Jimny Sierra",
      "Kei",
      "Khyber",
      "Kizashi",
      "Liana",
      "Lj80",
      "Margalla",
      "Mega Carry Xtra",
      "Mehran VX",
      "Mehran VXR",
      "MR Wagon",
      "Palette",
      "Palette Sw",
      "Potohar",
      "Ravi",
      "Samuari",
      "Sj410",
      "Solio",
      "Solio Bandit",
      "Spacia",
      "Swift",
      "Sx4",
      "Twin",
      "Vitara",
      "Wagon R",
      "Wagon R Stingray",
      "Others",
    ],
  },
});

const CarModel = new mongoose.model("CarModel", CarModelSchema);

module.exports = CarModel;
