const mongoose = require("mongoose");

const CarModelSchema = new mongoose.Schema({
  model: {
    type: String,
    require: true,
    enum: [
      "City IVTEC",
      "Civic VTi Oriel Prosmatec",
      "Civic EXi",
      "City IDSI",
      "City Aspire",
      "Alto",
      "Alto Lapin",
      "APV",
      "Baleno",
      "Bolan",
      "Cappuccino",
      "Carry",
      "Celerio",
      "Cervo",
      "Ciaz",
      "Cultus VX",
      "Cultus VXL",
      "Cultus VXR",
      "Escudo",
      "Every",
      "Every Wagon",
      "FX",
      "Hustler",
      "Ignis",
      "Jimny",
      "Jimny Sierra",
      "Kei",
      "Khyber",
      "Kizashi",
      "Liana",
      "Lj80",
      "Margalla",
      "Mega Carry Xtra",
      "Mehran VX",
      "Mehran VXR",
      "MR Wagon",
      "Palette",
      "Palette Sw",
      "Potohar",
      "Ravi",
      "Samuari",
      "Sj410",
      "Solio",
      "Solio Bandit",
      "Spacia",
      "Swift",
      "Sx4",
      "Twin",
      "Vitara",
      "Wagon R",
      "Wagon R Stingray",
    ],
  },
});

const CarModel = new mongoose.model("CarModel", CarModelSchema);

module.exports = CarModel;
