const mongoose = require("mongoose");

const CarRegistrationCitySchema = new mongoose.Schema({
  registrationCity: {
    type: String,
    require: true,
    enum: [
      "Lahore",
      "Karachi",
      "Islamabad",
      "Sindh",
      "Punjab",
      "Unregistered",
      "Abbottabad",
      "Ahmadpur East",
      "Ali Masjid",
      "Arifwala",
      "Askoley",
      "Attock",
      "Badin",
      "Bagh",
      "Bahawalnagar",
      "Bahawalpur",
      "Bannu",
      "Batagram",
      "Bela",
      "Bhakkar",
      "Bhimber",
      "Buner",
      "Charsadda",
      "Chichawatni",
      "Chilas",
      "Chiniot",
      "Chishtian Mandi",
      "Chitral",
      "Dadu",
      "Darra A,dam Khel",
      "Daska",
      "Dera Ghazi Khan",
      "Dera Ismail Khan",
      "Faisalabad",
      "Ghanche",
      "Ghizer",
      "Gilgit",
      "Gojra",
      "Gujranwala",
      "Gujrat",
      "Gwadar",
      "Hafizabad",
      "Hala",
      "Hangu",
      "Haripur",
      "Hasilpur",
      "Haveli lakha",
      "Hyderabad",
      "Islamabad",
      "Jacobabad",
      "Jamrud",
      "Jamshoro",
      "Jandola",
      "Jaranwala",
      "Jhang Sadar",
      "Jhelum",
      "Jiwani",
      "Kalat",
      "Kamoke",
      "Kandhura",
      "Karachi",
      "Karak",
      "Kasur",
      "Khairpur",
      "Khanewal",
      "Khanpur",
      "Khaplu",
      "Khushab",
      "Khuzdar",
      "Kohat",
      "Kohistan",
      "Kot Addu",
      "Lahore",
      "Lakki Marwat",
      "Landi Kotal",
      "Larkana",
      "Lasbela",
      "Layyah",
      "Lower Dir",
      "Malakand",
      "Mandi Bahauddin",
      "Mansehra",
      "Mardan",
      "Mianwali",
      "Mingaora",
      "Miram Shah",
      "Mirpur",
      "Mirpur Khas",
      "Mithi",
      "Multan",
      "Muridike",
      "Muzaffarabad",
      "Muzaffargarh",
      "Nawabshah",
      "Nowshera",
      "Okara",
      "Ormara",
      "Pakpattan",
      "Parachinar",
      "Pasni",
      "Peshawar",
      "Pirmahal",
      "Punjab",
      "Quetta",
      "Rahimyar Khan",
      "Ratodero",
      "Rawalpindi",
      "Sadiqabad",
      "Safdar Abad",
      "Sahiwal",
      "Sargodha",
      "Shangla",
      "Sheikhüpura",
      "Shikarpur",
      "Sialkot",
      "Sindh",
      "Skardu",
      "Sukkar",
      "Sukkur",
      "Swabi",
      "Swat",
      "Tando Adam",
      "Tank",
      "Thatta",
      "Toba Tek singh",
      "Torkham",
      "Upper Dir",
      "Vehari",
      "Wah",
      "Wana",
      "Wazirabad",
    ],
  },
});
const CarRegCity = new mongoose.model("CarRegCity", CarRegistrationCitySchema);

module.exports = CarRegCity;
