const Joi = require("joi");

const userSchema = Joi.object({
  username: Joi.string().required().min(3).max(40),

  first_name: Joi.string().required().min(3).max(40),

  last_name: Joi.string().required().min(3).max(40),

  email: Joi.string().email().required(),

  password: Joi.string().min(7).max(70).required(),

  phone_number: Joi.number().required(),

  latitude: Joi.number().when("zipcode", {
    is: undefined,
    then: Joi.required(),
  }),

  longitude: Joi.number().when("zipcode", {
    is: undefined,
    then: Joi.required(),
  }),

  city: Joi.string()
    .required()
    .valid(
      "Lahore",
      "Karachi",
      "Islamabad",
      "Sindh",
      "Punjab",
      "Unregistered",
      "Abbottabad",
      "Ahmadpur East",
      "Ali Masjid",
      "Arifwala",
      "Askoley",
      "Attock",
      "Badin",
      "Bagh",
      "Bahawalnagar",
      "Bahawalpur",
      "Bannu",
      "Batagram",
      "Bela",
      "Bhakkar",
      "Bhimber",
      "Buner",
      "Charsadda",
      "Chichawatni",
      "Chilas",
      "Chiniot",
      "Chishtian Mandi",
      "Chitral",
      "Dadu",
      "Darra A,dam Khel",
      "Daska",
      "Dera Ghazi Khan",
      "Dera Ismail Khan",
      "Faisalabad",
      "Ghanche",
      "Ghizer",
      "Gilgit",
      "Gojra",
      "Gujranwala",
      "Gujrat",
      "Gwadar",
      "Hafizabad",
      "Hala",
      "Hangu",
      "Haripur",
      "Hasilpur",
      "Haveli lakha",
      "Hyderabad",
      "Islamabad",
      "Jacobabad",
      "Jamrud",
      "Jamshoro",
      "Jandola",
      "Jaranwala",
      "Jhang Sadar",
      "Jhelum",
      "Jiwani",
      "Kalat",
      "Kamoke",
      "Kandhura",
      "Karachi",
      "Karak",
      "Kasur",
      "Khairpur",
      "Khanewal",
      "Khanpur",
      "Khaplu",
      "Khushab",
      "Khuzdar",
      "Kohat",
      "Kohistan",
      "Kot Addu",
      "Lahore",
      "Lakki Marwat",
      "Landi Kotal",
      "Larkana",
      "Lasbela",
      "Layyah",
      "Lower Dir",
      "Malakand",
      "Mandi Bahauddin",
      "Mansehra",
      "Mardan",
      "Mianwali",
      "Mingaora",
      "Miram Shah",
      "Mirpur",
      "Mirpur Khas",
      "Mithi",
      "Multan",
      "Muridike",
      "Muzaffarabad",
      "Muzaffargarh",
      "Nawabshah",
      "Nowshera",
      "Okara",
      "Ormara",
      "Pakpattan",
      "Parachinar",
      "Pasni",
      "Peshawar",
      "Pirmahal",
      "Punjab",
      "Quetta",
      "Rahimyar Khan",
      "Ratodero",
      "Rawalpindi",
      "Sadiqabad",
      "Safdar Abad",
      "Sahiwal",
      "Sargodha",
      "Shangla",
      "Sheikhüpura",
      "Shikarpur",
      "Sialkot",
      "Sindh",
      "Skardu",
      "Sukkar",
      "Sukkur",
      "Swabi",
      "Swat",
      "Tando Adam",
      "Tank",
      "Thatta",
      "Toba Tek singh",
      "Torkham",
      "Upper Dir",
      "Vehari",
      "Wah",
      "Wana",
      "Wazirabad"
    ),
}).unknown(true);

const validUserSchema = (req, res, next) => {
  const { error } = userSchema.validate(req.body, { abortEarly: false });
  if (error) {
    return res.status(400).json({ error });
  } else {
    next();
  }
};

module.exports = validUserSchema;
